# Generated by Django 6.0.3 on 2026-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_checklistitem_otp_permission_role_vehicletype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver_location_updated_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian cập nhật vị trí cuối cùng', null=True),
        ),
    ]
