# Generated by Django 6.0.3 on 2026-03-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='document_fee',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='emission_test_fee',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='stamp_fee',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='sticker_fee',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='vat_percent',
        ),
        migrations.AddField(
            model_name='pricing',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Phí đăng bộ'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Phí dịch vụ'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='inspection_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Phí đăng kiểm'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền'),
        ),
    ]
