# Generated by Django 6.0.3 on 2026-03-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pricing_document_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereturnlog',
            name='status',
            field=models.CharField(choices=[('draft', 'Khởi tạo - Draft'), ('vehicle_inspected', 'Đã kiểm tra xe'), ('condition_checked', 'Đã kiểm tra tình trạng'), ('inspection_expiry_updated', 'Đã cập nhật ngày hết hạn'), ('completed', 'Hoàn tất')], default='draft', help_text='Trạng thái biên bản', max_length=50),
        ),
    ]
