# Generated by Django 6.0.3 on 2026-03-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vehiclereturnlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('assigned', 'Đã phân công'), ('in_progress', 'Đang thực hiện'), ('vehicle_received', 'Đã nhận xe'), ('vehicle_returned', 'Đã trả xe'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Phí đường bộ'),
        ),
    ]
