# Generated by Django 6.0.3 on 2026-03-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_status_alter_pricing_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='inspection_fee',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Phí đăng kiểm'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Phí đường bộ'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Phí dịch vụ'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền'),
        ),
    ]
