# Generated by Django 6.0.3 on 2026-03-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pricing_inspection_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_legacy',
            field=models.CharField(blank=True, choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('assigned', 'Đã phân công'), ('in_progress', 'Đang thực hiện'), ('vehicle_received', 'Đã nhận xe'), ('vehicle_returned', 'Đã trả xe'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], help_text='DEPRECATED - Sử dụng status (FK) thay vì', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(help_text='Mã trạng thái (VD: pending, confirmed, assigned, v.v.)', max_length=30, unique=True)),
                ('status_name', models.CharField(help_text='Tên trạng thái hiển thị (VD: Chờ xử lý, Đã xác nhận)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về trạng thái này', null=True)),
                ('color_code', models.CharField(default='gray', help_text='Mã màu để hiển thị (orange, blue, green, red, v.v.)', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Thứ tự hiển thị trong danh sách')),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái này có đang hoạt động không')),
                ('is_terminal', models.BooleanField(default=False, help_text='Trạng thái cuối cùng (không thể chuyển sang trạng thái khác)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trạng thái đơn hàng',
                'verbose_name_plural': 'Trạng thái đơn hàng',
                'db_table': 'order_statuses',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['status_code'], name='order_statu_status__036738_idx'), models.Index(fields=['is_active'], name='order_statu_is_acti_8b739f_idx')],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Liên kết đến bảng order_statuses để quản lý trạng thái động', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.orderstatus'),
        ),
    ]
