# Generated by Django 6.0.3 on 2026-03-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_status_legacy_orderstatus_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_document',
            field=models.FileField(blank=True, help_text='File hợp đồng ủy quyền (DOCX)', null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_document_created_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian tạo hợp đồng', null=True),
        ),
    ]
