# Generated by Django 6.0.3 on 2026-03-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_contract_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian hoàn tất thanh toán', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản')], help_text='Phương thức thanh toán: cash/transfer', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', help_text='Trạng thái thanh toán: unpaid/paid', max_length=20),
        ),
    ]
