# Generated by Django 6.0.3 on 2026-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_payment_completed_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('vietqr', 'VietQR'), ('momo', 'Momo'), ('zalopay', 'ZaloPay'), ('vnpay', 'VNPay')], help_text='Phương thức thanh toán: cash/transfer', max_length=20, null=True),
        ),
    ]
