# Generated by Django 6.0.3 on 2026-03-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_vehiclereceiptlog_customer_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereturnlog',
            name='customer_signature',
            field=models.ImageField(blank=True, help_text='Chữ ký khách hàng (upload file)', null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='vehiclereturnlog',
            name='staff_signature',
            field=models.ImageField(blank=True, help_text='Chữ ký nhân viên (upload file)', null=True, upload_to='signatures/'),
        ),
    ]
