# Generated by Django 6.0.3 on 2026-04-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_seed_inspection_image_requirements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inspectionimagerequirement',
            new_name='inspection__stage_fa4362_idx',
            old_name='iir_stage_active_idx',
        ),
        migrations.RenameIndex(
            model_name='inspectionimagerequirement',
            new_name='inspection__categor_42a677_idx',
            old_name='iir_category_idx',
        ),
        migrations.RenameIndex(
            model_name='mediafile',
            new_name='media_files_order_i_750b3a_idx',
            old_name='media_order_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='mediafile',
            new_name='media_files_require_12d65c_idx',
            old_name='media_requirement_idx',
        ),
    ]
