# Generated by Django 6.0.4 on 2026-04-17 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_payment_payos_fields_and_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('total_top_up', models.BigIntegerField(default=0)),
                ('total_spent', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Số dư ví',
                'verbose_name_plural': 'Số dư ví',
                'db_table': 'wallet_balances',
            },
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('order_code', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('TOP_UP', 'Nạp tiền'), ('SPEND', 'Tiêu tiền'), ('REFUND', 'Hoàn tiền'), ('ADJUSTMENT', 'Điều chỉnh')], max_length=20)),
                ('amount', models.BigIntegerField()),
                ('balance_before', models.BigIntegerField(blank=True, null=True)),
                ('balance_after', models.BigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lịch sử ví',
                'verbose_name_plural': 'Lịch sử ví',
                'db_table': 'wallet_history',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('COMPLETED', 'Hoàn thành')], default='PENDING', max_length=20)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='api.payment')),
            ],
            options={
                'verbose_name': 'Hoàn tiền',
                'verbose_name_plural': 'Hoàn tiền',
                'db_table': 'refunds',
            },
        ),
    ]
