# Generated by Django 6.0.4 on 2026-04-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_wallet_and_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'db_table': 'transactions',
            },
        ),
    ]
