# Generated by Django 6.0.4 on 2026-04-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_staffnotificationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('vietqr', 'VietQR'), ('momo', 'Momo'), ('zalopay', 'ZaloPay'), ('vnpay', 'VNPay'), ('wallet', 'Ví điện tử')], help_text='Phương thức thanh toán: cash/transfer', max_length=20, null=True),
        ),
    ]
