# Generated by Django 6.0.4 on 2026-04-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_staff_notif_staff_i_27820f_idx_staff_notif_staff_i_73eb18_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffnotificationsetting',
            new_name='staff_notif_staff_i_73eb18_idx',
            old_name='staff_notif_staff_i_27820f_idx',
        ),
    ]
