# Generated by Django 6.0.4 on 2026-04-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_order_handover_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereturnadditionalcost',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('SUCCESS', 'Đã thanh toán'), ('FAILED', 'Thất bại'), ('CANCELLED', 'Đã hủy')], default='PENDING', help_text='Trạng thái thanh toán', max_length=20),
        ),
    ]
